### ISSUE TITLE
Eliminate redundant now() methods

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#102]
One in BlockManagementAgent, another in NamespaceProcessor, and a bunch of direct use of o.a.h.u.Time.now().
I propose to do static import of o.a.h.u.Time.now(), and use now() in the code. That way it will be easy to replace it with giraffa impl. of now() if needed.

**Comment by octo47** [comment]
There is another similar thing in hbase org.apache.hadoop.hbase.util.EnvironmentEdgeManager and it provides org.apache.hadoop.hbase.util.EnvironmentEdge. This interface has a couple of useful implementations to make it possible to control time.
HBase uses this EnvironmentEdge in many places, so we can write tests with controlled timestamps, that is good for testing edge situations of eventual consistency in our storage.

**Comment by shvachko** [comment]
I just removed the `now()` methods and imported `Time.now()` from hadoop.
See branch `issue-102` for review.
Good to know about HBase `EnvironmentEdge` Andrey. Funny how every project has same tools.

**Comment by shvachko** [comment]
Got an approval from Plamen for this.

**Comment by shvachko** [comment]
Just committed.
