### ISSUE TITLE
Change trunk SNAPSHOT version to 0.2

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#105]
Trunk should be 0.2-SNAPSHOT, rather than 0.1.1-SNAPSHOT

**Comment by shvachko** [comment]
Could you get rid of re-formatting changes, please.
They are not the subject of this issue.

**Comment by octo47** [comment]
That was done by mvn release:update-versions -DautoVersionSubmodules=true. 
I didn't do that by hand :).
Next time we will call this thing it will do the same.

**Comment by octo47** [comment]
done.

**Comment by shvachko** [comment]
Yeh, different tools format differently. My Eclipse would probably do something else. You can just edit the pom.xml files.
One more thing. The commit message should be like this:
Issue 105: Update trunk version to 0.2-SNAPSHOT. (Andrey)
vs. yours
issue-105 update version to 0.2-SNAPSHOT

**Comment by shvachko** [comment]
+1. Modular you amend the commit message before pushing.

**Comment by octo47** [comment]
So we need to have only one commit?
Not long ago amend with push -f did work properly with pull-requests.
Need to write contribute rules somewhere.

**Comment by shvachko** [comment]
Yes, the rules are here:
https://github.com/GiraffaFS/giraffa/wiki/Contribution#sharing-code-changes
Did you read them?

**Comment by octo47** [comment]
Now yes. Thank you.

**Comment by shvachko** [comment]
Just committed. Thank you Andrey.

**Comment by shvachko** [comment]
Forgot to add to CHANGES.txt. Should add on a next commit.
