### ISSUE TITLE
Make tool.jar available as dependency on different platforms.

### ISSUE THREAD

**Issue by octo47** [GiraffaFS/giraffa#114]
While working on HBase1.0 stumbled on a problem with antrun plugin. 
It does incorrect java_home resolving, so it can substitute correct
jdk home with jre home. 
Similar problem discussed here: http://stackoverflow.com/questions/2022622/java-home-gets-mangled-by-maven

**Comment by shvachko** [comment]
Is it HBase1.0 specific?
Why other Mac users don't see it? I am on Linux, so cannot see it.

**Comment by octo47** [comment]
That depend on what version of Java they use and did or not they created some symlinks in java installation.
That generally commonly used hack for maven.
Similar thing can be found in  hadoop-common-project/hadoop-annotations/pom.xml or hbase-annotations/pom.xml.

**Comment by shvachko** [comment]
I don't see "apple-jdk" anywhere.
@c0s could you look at it please.

**Comment by ghost** [comment]
Yeah, I think it's ok - after all when dealing with crap like Apple you have to be prepared for some nuts dances.

**Comment by octo47** [comment]
@shvachko, I didn't copy&paste from hadoop/hbase, that is just more correct way to handle discrepancy in java distributions

**Comment by ghost** [comment]
+1

**Comment by milandesai** [comment]
This doesn’t resolve the error for me, though it does for Plamen and Konstantin. I am still getting the same error where the JAVA_HOME is going to the jre and there’s no tools.jar as a result.

**Comment by octo47** [comment]
interesting, what command `ls $(/usr/libexec/java_home)/lib` shows?
and `/usr/libexec/java_home` too

**Comment by milandesai** [comment]
It shows a bunch of files, including tools.jar, but no classes.jar. Is it supposed to showing classes.jar?

**Comment by octo47** [comment]
No, it is ok. It should pick up tools.jar.
Hard to say what is broken, I'd try to set java_home using tool which report correct path to java.
May be that can help.

```
export JAVA_VERSION=1.7
export JAVA_HOME=$(/usr/libexec/java_home)
```

**Comment by milandesai** [comment]
Yeah that's exactly what I do right now. No worries - looking into the issue.

**Comment by shvachko** [comment]
Going to commit it now.

**Comment by shvachko** [comment]
Committed. Thank you Andrey.
