### ISSUE TITLE
Replace System.out.println() and printStackTrace() with LOG statements.

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#120]
We should use logging instead of `println()` and `printStackTrace()`.
Will need to define LOG variable in order to do that.
Saw in tests, but need to check everything.

**Comment by shvachko** [comment]
This looks good to me +1.

**Comment by octo47** [comment]
thank you, merged

**Comment by shvachko** [comment]
Andrey, you forgot to add the message into CHANGES.txt
Somebody else should add it on the next commit.
