### ISSUE TITLE
ArrayIndexOutOfBoundsException when calling getLocatedFileStatus on empty file

### ISSUE THREAD

**Issue by milandesai** [GiraffaFS/giraffa#130]
As @octo47 discovered after applying my Hadoop upgrade patch (Issue-94), we get ArrayIndexOutOfBoundsException when calling getLocatedFileStatus on empty file. This is especially a problem after doing the upgrade since create() now returns a LocatedFileStatus object, meaning every create call will throw this Exception. I created a new issue instead of incorporating the fix into upgrade because this is a separate bug.

**Comment by milandesai** [comment]
Created a pull request with the trivial fix and a test. This is a blocker for Issue 94.

**Comment by shvachko** [comment]
+1

**Comment by shvachko** [comment]
Just committed. Thank you Milan.
