### ISSUE TITLE
NamespaceProcessor throws NPE in renewLease().

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#136]
In `NamespaceProcessor.renewLease()` `leaseManager.renewLease()` returns null if there are no leases for the client. And then the for-loop throws NPE.
Should check not-null or return empty collection.

**Comment by pjeli** [comment]
Opened pull request. Pretty simple fix.

**Comment by shvachko** [comment]
+1 LGTM

**Comment by shvachko** [comment]
Committed. Thank you Plamen.
