### ISSUE TITLE
Fix post-upgrade warnings. 

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#140]
In HBase 1.0 some APIs that Giraffa used are deprecated. Should fix these warnings.
Some examples: HTableInterface extends Table, HBaseAdmin, put.add()...

**Comment by shvachko** [comment]
Also remove unused imports in `TestGiraffaFSContract`.

**Comment by milandesai** [comment]
Looks good, but a couple more minor things we can fix. In INodeManager.getListing(...), we shouldn't throw AccessControlException, FileNotFoundException, and UnresolvedLinkException. We can remove those and their imports. Additionally, in BlockManagementAgent, we can remove unused method getGiraffaBlockName(Block) and the import for Block. Other than that, looks good.

**Comment by shvachko** [comment]
- For INodeManager.getListing() I guess it is ok to remove those. We may need to restore them with future implementation of permissions and symLinks. Unless `NamespaceProcessor.getListing()` will take care of them.
- Good catch with getGiraffaBlockName(). Looks like only getGiraffaBlockPath() is needed.
- I also removed `getKeyValues()`. It doesn't look we need to copy Cells from the put anymore.

**Comment by milandesai** [comment]
Looks good, +1

**Comment by shvachko** [comment]
There are still a few warnings remaining btw, in `GiraffaWebServer` and `GiraffaWebObserver`. They related to the fact that HBase switched from a.o.h.HttpServer to HttpServer2. Will create another jira for that.

**Comment by shvachko** [comment]
Just committed.
