### ISSUE TITLE
Increase test case coverage for TestGiraffaCLI.

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#143]
During upgrade we reduced the passing rate for `TestGiraffaCLI` from 94% to 86%.
Some test cases can be fixed without introducing new functionality. Like white spaces in file paths.
Ask me if you need logs from a pre-upgrade CLI run. It is useful for the comparison.

**Comment by shvachko** [comment]
I fixed 7 more test cases for TestGiraffaCLI, which brought the success rate 1% up to 87%. Oh well.
Please review branch issue-143.

But it fixed an important bug related to the upgrade. HDFS 2.5 allows paths to end with "/", which made giraffa treat `/user/` and `/user` as different keys. I added normalization on the client side. The alternative is to normalize RowKey on the server side, but I think it should be client logic rather than server.
Also fixed `GiraffaAdmin help -report`, which changed in 2.5. `GiraffaAdmin` is a full copy-pasta of DFSAdmin, we should do something about it at some point.

**Comment by pjeli** [comment]
+1; Changes all make sense and CLI test passes.

**Comment by shvachko** [comment]
Just committed this.
