### ISSUE TITLE
Use RetryingCallerInterceptor to handle Exceptions

### ISSUE THREAD

**Issue by milandesai** [GiraffaFS/giraffa#149]
Currently, we implement our own makeshift RpcRetryingCaller to avoid retrying filesystem exceptions. With HBase 1.0, a better way is to use an Interceptor that captures Exceptions thrown by the server and rethrows them if they are filesystem-related. This allows non-filesystem related Exceptions to be processed normally and avoids rewriting the RPC retrying implementation.

**Comment by shvachko** [comment]
Great. Simplifies things. We probably can move `GiraffaRpcRetryingCallerFactory` inside `org.apache.hadoop.hbase.client` package, and then `FileSystemExceptionInterceptor` can be a static sub class inside the factory.

**Comment by shvachko** [comment]
I moved `GiraffaRpcRetryingCallerFactory` under `hbase.client` and merged everything in one class.

**Comment by shvachko** [comment]
Committed. Thank you, Milan.
