### ISSUE TITLE
NamespaceAgent can fail operations when RegionServer dies

### ISSUE THREAD

**Issue by pjeli** [GiraffaFS/giraffa#153]
This was discovered from working on issue #132; specifically the unit test from there, post issue #122, revealed that a GiraffaClient fails to makes calls after a RegionServer has been killed.

This is mainly due to the change in HBase client code. GiraffaClient has been changed to use  Connection and Table interfaces in place of HTable. However, it appears that this change has in turn made the client rely on a particular RegionServer.

Seems we need to always grab a new Table whenever we need to make a call rather than rely on the same Table every time.

**Comment by pjeli** [comment]
This issue needs to be resolved before we can do issue #132.

**Comment by shvachko** [comment]
Would be good for Milan to look at this as he was doing the exception handling.

**Comment by milandesai** [comment]
Looks good, +1

**Comment by shvachko** [comment]
The unit tests are failing with this fix. Looks like  you are catching some exceptions that don't need to be switched over, or switching goes too long. As the result some services are not quitting when one test ends, and that makes subsequent tests fail.

**Comment by shvachko** [comment]
I merged Plamen's patch into current trunk, which has Milan's ExceptionInterceptor and all tests seems to be passing, see in the branch. Will try it with TestLease from #132

**Comment by shvachko** [comment]
Tests for issue #132 are passing. Will commit this now.

**Comment by shvachko** [comment]
Committed. Thank you Plamen.
