### ISSUE TITLE
Introduce GiraffaConfiguration.getGiraffaTableName()

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#156]
Giraffa table name is used in many places. Let's unify this by introducing:

```
public static String GiraffaConfiguration.getGiraffaTableName(Configuration conf);
```

**Comment by milandesai** [comment]
I have given this issue to Wei-Lin. He is not in the system yet so I am temporarily assigning it to me to avoid confusion.

**Comment by shvachko** [comment]
The patch looks good. Few minor things:
1. Use `import static GiraffaConfiguration.getGiraffaTableName`. Then you can call `getGiraffaTableName()` instaed of `GiraffaConfiguration.getGiraffaTableName()`.
2. Fix long lines (should be <= 80 symbols)

**Comment by weilintsaiWand** [comment]
Revision done at 3rd commit. Thanks.

**Comment by shvachko** [comment]
I was not precise about (2), which meant not to introduce new long lines, while the long lines unrelated to the patch should remain as is. We can file a different issue to reformat all long lines. But this one should stick to its goal, that is introduce `getGiraffaTableName()`. So let's go over one more iteration here. Minimizing code changes will be important, when we will have to support multiple versions, and changes should be promoted between them.

**Comment by weilintsaiWand** [comment]
Thanks Konstantin. The revised code is ready at 4th commit

**Comment by shvachko** [comment]
Found two more places where we can use `getGiraffaTableName()`: `htable.jsp` and `index.jsp`. See under `resources/hbase-webapps/giraffa`

**Comment by weilintsaiWand** [comment]
Updated at 5th commit. Thanks.

**Comment by shvachko** [comment]
Now you can remove `import GiraffaConfiguration` from the two jsp files.
Looks good otherwise.

**Comment by shvachko** [comment]
Also Wei-Lin you need to [install the pre-commit hook](https://github.com/GiraffaFS/giraffa/wiki/Contribution#configuring-pre-commit-hook). We use git commits to generate release notes, so the format of log messages is important.

**Comment by shvachko** [comment]
I removed the imports of GiraffaConfiguration, and committed.
Congratulations Wei-Lin.
