### ISSUE TITLE
NamespaceAgent should log filesystem Exceptions at debug level

### ISSUE THREAD

**Issue by milandesai** [GiraffaFS/giraffa#163]
Currently, NamespaceAgent logs any encountered Exceptions from filesystem calls at INFO level, which is unnecessary and results in nasty looking logs for innocuous Exceptions (such as FileNotFoundException before a file is created, etc.). The logging level should be changed to DEBUG.

**Comment by shvachko** [comment]
+1

**Comment by milandesai** [comment]
Committed to trunk as `044522f91818b6f50f53b68bb13bd44a746f334d`
