### ISSUE TITLE
Update POM to Java 7

### ISSUE THREAD

**Issue by milandesai** [GiraffaFS/giraffa#181]
Our pom file unnecessarily restricts us to Java 6, which means we can't use Java 7 features such as Diamonds and multi-catch. Let's bump this to Java 7.

To take advantage of Java 7 features, all project members using IntelliJ should ensure that in the Project Structure window, the Project SDK is configured for 1.7 and the Project Language Level is configured for 7. All project members should actively use diamonds and multi-catch when applicable in new patches.

**Comment by milandesai** [comment]
Created pull request with trivial change. Encountered no problems with build.

**Comment by pjeli** [comment]
+1. Let's do this. Will have to update Jenkins build afterwards as right now its using 1.6.

**Comment by shvachko** [comment]
Committed. Thanks, Milan.
Let's not forget to update Jenkins.
