### ISSUE TITLE
Unused member monitor in NamespaceProcessor.

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#183]
`NamespaceProcessor.monitor` is never used, should be removed. Was introduced by #133.

**Comment by pjeli** [comment]
+1.

**Comment by weilintsaiWand** [comment]
+1

**Comment by shvachko** [comment]
Changes are:
1. Removed `NamespaceProcessor.monitor` member.
2. Renamed `getMonitor()` to `initializeMonitor()` because this is what it does.
3. Replaced `Preconditions` with assert. Let's not introduce unnecessary dependencies, it is hard get rid of them.

Thanks for the reviews, guys.

**Comment by shvachko** [comment]
Committed.
