### ISSUE TITLE
Replace README.txt with README.md and add "Requirements" section.

### ISSUE THREAD

**Issue by dsalychev** [GiraffaFS/giraffa#191]
Compilation error with protoc version 2.6.1
Sure, I have to compile it with 2.5.0 version, but I think it's ok to mention it in README.txt.

**Comment by weilintsaiWand** [comment]
How about mentioning  hbase-1.0.1 and hadoop-2.5.1?

Btw, I've update wiki page
https://github.com/GiraffaFS/giraffa/wiki/Introduction-and-requirements-for-Giraffa
https://github.com/GiraffaFS/giraffa/wiki/How-to-Setup,-Build,-and-Use-Giraffa

**Comment by dsalychev** [comment]
I think, they are hbase-1.0.0+ and hadoop-2.5.0+, aren't they?

**Comment by shvachko** [comment]
Good idea to update README.
Let's say Java 1.7+. Because
- 1.6 is end of life, and 
- there are some changes coming, which will be 1.7 specific. As in #188 `Array<>` construct requires Java >= 1.7. Not that we cannot avoid it, but supporting 1.6 is a restriction at this point.

**Comment by shvachko** [comment]
You also need to amend the commit message. It should be formatted as described in step 6 of
https://github.com/GiraffaFS/giraffa/wiki/Contribution#sharing-code-changes
Also pre-commit hook should help:
https://github.com/GiraffaFS/giraffa/wiki/Contribution#configuring-pre-commit-hook

**Comment by weilintsaiWand** [comment]
Looks good. Only one quick question: I see README.txt is still existed, should we delete it ?

**Comment by dsalychev** [comment]
I removed it, just forgot to remove it within first commit.

**Comment by shvachko** [comment]
I just committed this. Congratulations Dmitry!

For the future. It is ok to put multiple commits in the same push request. They will be squashed into a single commit anyways.
