### ISSUE TITLE
Fix Jenkins build following Protobuf changes 

### ISSUE THREAD

**Issue by pjeli** [GiraffaFS/giraffa#201]
Jenkins build is failing with a bunch of "protoc" related Exceptions. Need to fix to allow build to run normally locally and with parameters on Jenkins.

**Comment by shvachko** [comment]
+1 Worked for me.

**Comment by pjeli** [comment]
Committed into trunk as 0d1c0794918850380ec988bc5467f4a99d0a14a8.
Changing Jenkins build.

**Comment by pjeli** [comment]
Jenkins TRUNK and RELEASE builds changed. Done.
