### ISSUE TITLE
Null pointer exception in the fix of #196 in checkFileClosed() method

### ISSUE THREAD

**Issue by weilintsaiWand** [GiraffaFS/giraffa#203]
I made a mistake in the fix of #196, on line 455 of BlockManagementAgent.java. nodeInfo's content can be null since the node is not created yet. As a result, if we want to get FileState of that INode, it would get  an null pointer exception. 
Please refer to the patch for details.

**Comment by weilintsaiWand** [comment]
The hot fix is ready. Please note that before this patch, most of test would fail. 
With this patch, all tests pass.

**Comment by pjeli** [comment]
Would the .getRow() return null or the Result itself be null? Seems kinda silly that .getRow() would return null if the entire row doesn't exist.

I think you can also try to make use of Result.isEmpty() instead of the null check.

**Comment by weilintsaiWand** [comment]
It seems like nodeInfo itself is never null. Although I did not check each item, but most variable of nodeInfo is null if we can not get a row from HBase. I agree that nodeInfo.isEmpty() is more readable. I will update it after it passes regression.

**Comment by weilintsaiWand** [comment]
Regression pass and new version is committed.
