### ISSUE TITLE
Fix Jenkins build post-121

### ISSUE THREAD

**Issue by pjeli** [GiraffaFS/giraffa#212]
Issue #121 moves the project to using Gradle but it has some implications on our Jenkins build.

One thing in particular to fix next is to make it able to utilize a custom protobuf compiler since CloudBees does not allow us to use a permanent protobuf installation.

**Comment by milandesai** [comment]
+1

**Comment by pjeli** [comment]
Committed as: b1735c92a32233f234b91e91e1f9d23e65c02868.
