### ISSUE TITLE
Fix README.md and wiki following Gradle-ization

### ISSUE THREAD

**Issue by pjeli** [GiraffaFS/giraffa#214]
Now that the project is gradle-ized as of Issue #121 we need to update documentation in certain places.

**Comment by pjeli** [comment]
Website wikis has been changed to reflect Gradle-ization. Couple things I still need to address:
- Moving from Clover to JaCoCo.
- Need to make some sort of `mvn clean site` equivalent in our gradle build.
- Update README.md.

**Comment by pjeli** [comment]
I've opened an issue to address the JaCoCo movement: #215.

I'll add a pull request shortly that will make it so all you need to generate code coverage reports is to run: `./gradlew clean test jacocoTestReport` and then open up the following file: `giraffa/giraffa-core/build/reports/jacoco/test/html`

**Comment by pjeli** [comment]
Made pull request to fix README.md file.

Need to address:
- Giraffa Web UI failing (Issue #88).
- Lack of `mvn clean site` equivalent.

**Comment by milandesai** [comment]
+1

**Comment by pjeli** [comment]
Commited as: c17356200734062d7723e3fe4be4fd819d5bb0fb.
Closing.
