### ISSUE TITLE
Replace Clover with JaCoCo for code coverage

### ISSUE THREAD

**Issue by pjeli** [GiraffaFS/giraffa#215]
Clover requires a license to use and is complicated to set-up.

JaCoCo is free and very simple to set-up now that we've gradle-ized.

We should make the switch!

**Comment by pjeli** [comment]
All we need to do to support JaCoCo is add it as a gradle plugin to giraffa-core; literally a one-line change.

Then we just run the following commands:
`./gradlew clean test jacocoTestReport`

And in giraffa-core/build/reports/ there will be a new jacoco directory which will have an HTML generated report.

**Comment by milandesai** [comment]
+1

**Comment by pjeli** [comment]
Thanks @milandesai.

Committed as: 2a38df17013132352d042270f3cc67a160281dda.
