### ISSUE TITLE
Capital letter problem when formatting Giraffa

### ISSUE THREAD

**Issue by herrlich** [GiraffaFS/giraffa#223]
When we run the following command "bin/giraffa format", there will be a request "Re-format Giraffa file system ? (Y or N) ", if we type a lower case "y" here, it will return "Format aborted", so we may need to change the code to support both 'Y' and 'y'

**Comment by herrlich** [comment]
This will be fixed soon.

**Comment by shvachko** [comment]
+1 on the patch. Could you guys commit it, please.

**Comment by shvachko** [comment]
I just committed this. Congratulations Yuxiang!
