### ISSUE TITLE
Implement distributed unique ID generation

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#35]
Original [issue 35](https://code.google.com/p/giraffa/issues/detail?id=35) created by shvachko on 2012-09-21T05:38:39.000Z:

We need a method of generating unique IDs for a distributed system. It would be best if they were increments of unique IDs (so root is 1, /user is 2, /user/plamen is 3, etc), but a single random unique ID at a time works too.

This is needed in order to implement NumberedRowKey.

**Comment by shvachko** [comment]
Comment [#4](https://code.google.com/p/giraffa/issues/detail?id=35#c4) originally posted by shvachko on 2012-09-25T08:03:09.000Z:

Each BlockManagerProcessor should obtain a range of IDs. This could be coordinated by ZK or derived from the region server number and the total count of servers.
Then BlockManagerProcessor will incrementally assign the ids from that range. The ranges of used ids should be persisted either in ZK again or in a giraffa master state table or in HDFS. 
Needs design.

**Comment by shvachko** [comment]
Comment [#5](https://code.google.com/p/giraffa/issues/detail?id=35#c5) originally posted by shvachko on 2012-10-18T18:07:43.000Z:

&lt;empty&gt;

**Comment by shvachko** [comment]
Comment [#6](https://code.google.com/p/giraffa/issues/detail?id=35#c6) originally posted by shvachko on 2013-01-10T23:52:28.000Z:

We talked today that Hadoop 2 implements INode IDs, is this true? Will we be able to use them as OUR INode IDs?

**Comment by shvachko** [comment]
Comment [#7](https://code.google.com/p/giraffa/issues/detail?id=35#c7) originally posted by shvachko on 2013-08-02T20:00:47.000Z:

So basically this will come down to generating ranges of IDs to use for INodes.

Each RegionServer should maintain a flexible range of IDs (long values) that can be shrunken and expanded based on information (count of current RegionServers) from the HBaseMaster / ZooKeeper cluster.

Using this range we can generate unique IDs for INodes.

**Comment by shvachko** [comment]
Comment [#8](https://code.google.com/p/giraffa/issues/detail?id=35#c8) originally posted by shvachko on 2014-08-30T00:10:35.000Z:

Milan and I discussed how to do this today. We both decided on using Netflix's Curator library (via Apache, now Apache Curator).

The full code needed to support a sequential atomic long looks like:
{{{
curatorFramework = CuratorFrameworkFactory.newClient("host:port", new RetryNTimes(100, 10));
curatorFramework.start();

DistributedAtomicLong daLong = new DistributedAtomicLong(curatorFramework, "/number", new RetryNTimes(100, 10));

da.increment().value();
}}}

**Comment by milandesai** [comment]
Created a pull request containing just the ID field and generator, as discussed in #34.

**Comment by shvachko** [comment]
The idea here should be that we use sequential ++ until the segment runs out. Then we allocate the next segment. Using ZK to coordinate next segment allocation is fine for now, but ZK should not leak into `INodeIdGenerator`. So,
1. `INodeIdGenerator` should be in giraffa package.
2. `INodeIdGenerator` should implement `o.a.h.util.IdGenerator` or if possible even `o.a.h.util.SequentialNumber`. 
3. We will use the same generator for blockIds and genStamps in block management. So it would be good have a generic class for that logic. You can check the hierarchy for inodeId, blockId, and genStamp in Hadoop as an example.

**Comment by milandesai** [comment]
Updated branch to use a segmented approach to id generation. Tests are passing.

**Comment by shvachko** [comment]
Like the change. The hierarchy of ID classes looks somewhat over-engineered.
- Let's rename `DistributedId` to `IdGeneratorService`

```
interface IdGeneratorService extends IdGenerator {
  initialize();
  stop();
}
```
- `ZookeeperId` -> `ZKSequentialNumber implements IdGeneratorService`
- `SegmentedId` -> `SegmentedIdGenerator implements IdGenerator`
  Implementation of `SegmentedIdGenerator` uses `IdGeneratorService` as you wrote, but is not a service itself.
- `DistributedINodeId` is redundant, we can remove it.
- In `INodeManager` the new member should be

```
private IdGenerator inodeIdGenerator;
```

You first instantiate `ZKSequentialNumber`, initialize it, and pass to `SegmentedIdGenerator` ctor.
That way we will be able to make `ZKSequentialNumber` configurable as a service.
- Also would be good to add JavaDoc.

**Comment by milandesai** [comment]
Thanks @shvachko, I push changes based on your comments to the branch.

**Comment by shvachko** [comment]
Let's add back `IdGeneratorService.getInitialValue()`. My fault I missed it in my previous comment. This will let us avoid duplicating the initial value of the service inside `SegmentedIdGenerator`.

**Comment by milandesai** [comment]
Added back. Tests are still passing.

**Comment by shvachko** [comment]
+1

**Comment by milandesai** [comment]
Committed to trunk as `3b9b60cc0d49c6340ce75f8041e8716ec6a7d22c`.
