### ISSUE TITLE
Fix warnings and style issues

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#97]
Original [issue 97](https://code.google.com/p/giraffa/issues/detail?id=97) created by shvachko on 2015-04-15T18:54:11.000Z:

There are numerous compiler and IntelliJ warnings in the code that we should fix. There are also many style issues (spacing, indentation, method ordering, etc.) that we should resolve.

**Comment by octo47** [comment]
Should we publish what code style we are using? 
If we agree on some common settings like https://github.com/apache/hbase/blob/master/dev-support/hbase_eclipse_formatter.xml this issue will be much easier to solve and maintain this style later.

**Comment by shvachko** [comment]
Closing as a duplicate of #104.
